# baseURL = 'https://doughnutnz.github.io/childtherapy/'
baseURL = 'https://www.shorekidstherapy.co.nz/'

# This is a "one page"-website, so we do not need these kinds of pages...
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

# languageCode = 'en-us'
defaultContentLanguage = "en"

# The name of this wonderful theme.
theme = "scroll"

# The "title" of your website
title = 'Catherine Hunt - Registered Child and Adolescent Psychotherapist (interim scope) with Psychotherapists Board of Aotearoa New Zealand (PBANZ)'

[params]
    # A "copyright"-line to be added at the bottom of the page.
    # Hint: Markdown is supported in here as well. So you may e.g. add a link to your legal imprint-page.
    copyright = "Copyright Catherine Hunt, 2022"

    # The "description" of your website. This is used in the meta data of your generated html.
    description = "Child and Adolescent Psychotherapy"

    # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
    favicon = "images/favicon.png"

    # These "images" are used for the structured data templates. This will show up, when
    # services like Twitter or Slack want to generate a preview of a link to your site.
    # See https://gohugo.io/templates/internal#twitter-cards and
    # https://gohugo.io/templates/internal#open-graph.
    images = ["images/Background04.jpg"]

    # Another "title" :-). This one is used as the site_name on the Hugo's internal
    # opengraph structured data template.
    # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
    title = "Catherine Hunt - Registered Child and Adolescent Psychotherapist (interim scope) with Psychotherapists Board of Aotearoa New Zealand (PBANZ)"

    # This theme will, by default, inject a design-by-line at the bottom of the page.
    # You can turn it off, but we would really appreciate if you dont
    hidedesignbyline = true

    [params.meta]
        keywords = """\
                   child psychotherapy, \
                   adolescent psychotherapy, \
                   teen psychotherapy, \
                   auckland psychotherapy, \
                   anger issues, \
                   canine assisted psychotherapy, \
                   equine assisted psychotherapy, \
                   family based psychotherapy, \
                   anxiety, \
                   separation anxiety, \
                   social anxiety, \
                   depression, \
                   relationship difficulties, \
                   parental separation, \
                   grief, \
                   behaviour problems, \
                   bullying, \
                   school refusal, \
                   eating disorders, \
                   abuse \
                   """